export const categories = [
  { id: 'all', label: 'All' },
  { id: 'marketing', label: 'Marketing' },
  { id: 'management', label: 'Management' },
  { id: 'hr', label: 'HR & Recruiting' },
  { id: 'design', label: 'Design' },
  { id: 'development', label: 'Development' },
];

const img = (slug) => `assets/courses/${slug}.png`;

export const courses = [
  // --- Первый экран макета (9 карточек) ---
  {
    id: 1,
    title: 'The Ultimate Google Ads Training Course',
    category: 'marketing',
    price: 100,
    author: 'Jerome Bell',
    image: img('google-ads'),
  },
  {
    id: 2,
    title: 'Product Management Fundamentals',
    category: 'management',
    price: 480,
    author: 'Marvin McKinney',
    image: img('product-management'),
  },
  {
    id: 3,
    title: 'HR Management and Analytics',
    category: 'hr',
    price: 200,
    author: 'Leslie Alexander Li',
    image: img('hr-analytics'),
  },
  {
    id: 4,
    title: 'Brand Management & PR Communications',
    category: 'marketing',
    price: 530,
    author: 'Kristin Watson',
    image: img('brand-pr'),
  },
  {
    id: 5,
    title: 'Graphic Design Basic',
    category: 'design',
    price: 500,
    author: 'Guy Hawkins',
    image: img('graphic-design'),
  },
  {
    id: 6,
    title: 'Business Development Management',
    category: 'management',
    price: 400,
    author: 'Dianne Russell',
    image: img('business-development'),
  },
  {
    id: 7,
    title: 'Highload Software Architecture',
    category: 'development',
    price: 600,
    author: 'Brooklyn Simmons',
    image: img('highload-architecture'),
  },
  {
    id: 8,
    title: 'Human Resources — Selection and Recruitment',
    category: 'hr',
    price: 150,
    author: 'Kathryn Murphy',
    image: img('hr-recruitment'),
  },
  {
    id: 9,
    title: 'User Experience. Human-centered Design',
    category: 'design',
    price: 240,
    author: 'Cody Fisher',
    image: img('ux-design'),
  },

  // --- Дополнительные курсы (раскрываются по «Load more») ---
  {
    id: 10,
    title: 'Content Marketing Strategy',
    category: 'marketing',
    price: 260,
    author: 'Cameron Williamson',
    image: img('google-ads'),
  },
  {
    id: 11,
    title: 'Social Media Marketing',
    category: 'marketing',
    price: 310,
    author: 'Jane Cooper',
    image: img('brand-pr'),
  },
  {
    id: 12,
    title: 'Agile Project Management',
    category: 'management',
    price: 420,
    author: 'Robert Fox',
    image: img('product-management'),
  },
  {
    id: 13,
    title: 'Talent Acquisition Essentials',
    category: 'hr',
    price: 180,
    author: 'Esther Howard',
    image: img('hr-recruitment'),
  },
  {
    id: 14,
    title: 'People Management & Culture',
    category: 'hr',
    price: 230,
    author: 'Wade Warren',
    image: img('hr-analytics'),
  },
  {
    id: 15,
    title: 'Effective Onboarding',
    category: 'hr',
    price: 140,
    author: 'Courtney Henry',
    image: img('hr-recruitment'),
  },
  {
    id: 16,
    title: 'Frontend Development with React',
    category: 'development',
    price: 350,
    author: 'Devon Lane',
    image: img('highload-architecture'),
  },
  {
    id: 17,
    title: 'Scalable Backend Systems',
    category: 'development',
    price: 450,
    author: 'Theresa Webb',
    image: img('highload-architecture'),
  },
];
